export const ADD_CHORE = 'ADD_CHORE';
export const DELETE_CHORE = 'DELETE_CHORE';
export const EDIT_CHORE = 'EDIT_CHORE';
export const COMPLETE_CHORE = 'COMPLETE_CHORE';

export const ADD_BEHAVIOR = 'ADD_BEHAVIOR';
export const DELETE_BEHAVIOR = 'DELETE_BEHAVIOR';
export const EDIT_BEHAVIOR = 'EDIT_BEHAVIOR';

export const ADD_BEHAVIORQ = 'ADD_BEHAVIORQ';
export const DELETE_BEHAVIORQ = 'DELETE_BEHAVIORQ';
export const APPROVE_BEHAVIORQ = 'APPROVE_BEHAVIORQ';

export const ADD_REWARD = 'ADD_REWARD';
export const DELETE_REWARD = 'DELETE_REWARD';
export const EDIT_REWARD = 'EDIT_REWARD';

export const ADD_REWARDSQ = 'ADD_REWARDSQ';
export const DELETE_REWARDSQ = 'DELETE_REWARDSQ';
export const APPROVE_REWARDSQ = 'APPROVE_REWARDSQ';

export const ADD_POINTS = 'ADD_POINTS';

export const ADD_SETTING = 'ADD_SETTING';
export const DELETE_SETTING = 'DELETE_SETTING';
export const EDIT_SETTING = 'EDIT_SETTING';

export const RESET_SETTINGS = 'RESET_SETTINGS';
export const RESET_CHORES = 'RESET_CHORES';
export const RESET_BEHAVIORS = 'RESET_BEHAVIORS';
export const RESET_BEHAVIORQ = 'RESET_BEHAVIORQ';
export const RESET_REWARDS = 'RESET_REWARDS';
export const RESET_REWARDSQ = 'RESET_REWARDSQ';
